using System;
namespace ClinicService.IdentityServer.Constants
{
    public enum FunctionsConstant
    {
        DASHBOARD,

        CONTENT,
        CONTENT_WEBSITE_SECTION,
        CONTENT_SPECIALTY,
        CONTENT_CLINIC_BRANCH,
        CONTENT_MEDICAL_SERVICE,

        SYSTEM,
        SYSTEM_FUNCTION,
        SYSTEM_PERMISSION,
        SYSTEM_ROLE,
        SYSTEM_USER,

        CATEGORY,
        CATEGORY_PAYMENT_METHOD,
        CATEGORY_STATUS_CATEGORY,
        CATEGORY_MEDICAL_SERVICE_TYPE,

        STATISTIC,
        STATISTIC_MONTHLY_PERSONNEL,
        STATISTIC_MONTHLY_APPOINTMENT,
        STATISTIC_MONTHLY_NEWMEMBER,

        PERSONNEL,
        PERSONNEL_PATIENT,
        PERSONNEL_DOCTOR,

        PAYMENT,

        ADMINISTRATION,
        ADMINISTRATION_MEDICAL_EXAMINATION,
        ADMINISTRATION_REAPPOINTMENT,
        ADMINISTRATION_APPOINTMENT,
    }
}
